/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as NoticeBoardRouteImport } from './routes/notice-board'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestIdRouteImport } from './routes/request.$id'
import { Route as NewTypeRouteImport } from './routes/new.$type'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeBoardRoute = NoticeBoardRouteImport.update({
  id: '/notice-board',
  path: '/notice-board',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestIdRoute = RequestIdRouteImport.update({
  id: '/request/$id',
  path: '/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewTypeRoute = NewTypeRouteImport.update({
  id: '/new/$type',
  path: '/new/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/my-requests': typeof MyRequestsRoute
  '/notice-board': typeof NoticeBoardRoute
  '/use-cases': typeof UseCasesRoute
  '/new/$type': typeof NewTypeRoute
  '/request/$id': typeof RequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/my-requests': typeof MyRequestsRoute
  '/notice-board': typeof NoticeBoardRoute
  '/use-cases': typeof UseCasesRoute
  '/new/$type': typeof NewTypeRoute
  '/request/$id': typeof RequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/my-requests': typeof MyRequestsRoute
  '/notice-board': typeof NoticeBoardRoute
  '/use-cases': typeof UseCasesRoute
  '/new/$type': typeof NewTypeRoute
  '/request/$id': typeof RequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/how-it-works'
    | '/login'
    | '/my-requests'
    | '/notice-board'
    | '/use-cases'
    | '/new/$type'
    | '/request/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/how-it-works'
    | '/login'
    | '/my-requests'
    | '/notice-board'
    | '/use-cases'
    | '/new/$type'
    | '/request/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/how-it-works'
    | '/login'
    | '/my-requests'
    | '/notice-board'
    | '/use-cases'
    | '/new/$type'
    | '/request/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MyRequestsRoute: typeof MyRequestsRoute
  NoticeBoardRoute: typeof NoticeBoardRoute
  UseCasesRoute: typeof UseCasesRoute
  NewTypeRoute: typeof NewTypeRoute
  RequestIdRoute: typeof RequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice-board': {
      id: '/notice-board'
      path: '/notice-board'
      fullPath: '/notice-board'
      preLoaderRoute: typeof NoticeBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$id': {
      id: '/request/$id'
      path: '/request/$id'
      fullPath: '/request/$id'
      preLoaderRoute: typeof RequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/$type': {
      id: '/new/$type'
      path: '/new/$type'
      fullPath: '/new/$type'
      preLoaderRoute: typeof NewTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MyRequestsRoute: MyRequestsRoute,
  NoticeBoardRoute: NoticeBoardRoute,
  UseCasesRoute: UseCasesRoute,
  NewTypeRoute: NewTypeRoute,
  RequestIdRoute: RequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
